name: Example call
on:
  workflow_dispatch:
    inputs:
      version-number:
        required: true
        type: string
jobs:
  setup_credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: kthai-nr/newrelic-cordova-plugin
      - name: Setup GitHub Credentials
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git config --list
      - name: run_other_workflow
        uses: ./.github/workflows/update_android_agent.yml
        with:
          version-number: ${{ github.event.inputs.version-number }}
