name: Example call
on:
  workflow_dispatch:
    inputs:
      version-number:
        required: true
        type: string
jobs:
  call:
    uses: ./.github/workflows/update_android_agent.yml
    with:
      version-number: ${{ github.event.inputs.version-number }}
